entry_table_id = 0
entry_name_field = "Name"
entry_genre_field = "Genre"
entry_title_field = "Titel"
entry_duration_field = "Dauer"
entry_description_field = "Beschreibung"
location_table_id = 0
location_name_field = "Name"
timetable_table_id = 0
timetable_datetime_field = "Wann"
timetable_entry_field = "Beitrag"
timetable_location_field = "Spielstätte"
timetable_is_permanent_field = "Permanent?"